FROM microsoft/dotnet:2.1-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["AKSBackEnd/AKSBackEnd.csproj", "AKSBackEnd/"]

RUN dotnet restore "AKSBackEnd/AKSBackEnd.csproj"
COPY . .
WORKDIR "/src/AKSBackEnd"
RUN dotnet build --no-restore "AKSBackEnd.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]